### ISSUE TITLE
Updated version of motion interpolation scripts!

### ISSUE THREAD

**Issue by vioo-bkp** [maoiscat/mpv-mvtools-script#1]
Hello there,
If you dont mind, could you provide us an updated version of those 3 scripts?
Like to be more efficient, less artefacts and better quality?
Thanks!

**Comment by maoiscat** [comment]
no updates. currently ''mvtools_3'' is the most balanced one for my daily playback.
besides mvtools itself hasn't been updated for years.




---- Replied Message ----
| From | ***@***.***> |
| Date | 04/30/2023 19:36 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [maoiscat/mpv-mvtools-script] Updated version of motion interpolation scripts! (Issue #1) |

Hello there,
If you dont mind, could you provide us an updated version of those 3 scripts?
Like to be more efficient, less artefacts and better quality?
Thanks!

**Comment by vioo-bkp** [comment]
Thank you for letting us know. I appreciate your recommendation of 'mvtools_3' for daily playback. It's good to know that it's currently the most balanced option. And thank you for keeping us up-to-date in case there are any modifications in the future.
